[package]
name = "clipboard-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "clipboard-client"
path = "src/main.rs"

[dependencies]
clap = "2.33.3"
copypasta = "0.7.1"
